const LATIN = /[A-Za-z]/;
const LEADING_SYMBOLS = /^[^\p{L}\p{N}]+/u;

/** Arabic names for the scent notes used across the catalogue, keyed by lowercase English name. */
const ARABIC_NOTE_NAMES: Record<string, string> = {
  accord: 'التناغم',
  agarwood: 'العود',
  akigalawood: 'خشب الأكيغالا',
  aldehydes: 'الألدهيدات',
  algae: 'الطحالب',
  almond: 'اللوز',
  'almond cream': 'كريمة اللوز',
  'almond milk': 'حليب اللوز',
  aloe: 'الصبار',
  amaretto: 'الأمارتو',
  amber: 'العنبر',
  ambergris: 'العنبر الرمادي',
  amberwood: 'خشب العنبر',
  ambrette: 'الأمبريت',
  ambrettolide: 'أمبريتوليد',
  ambrofix: 'أمبروفيكس',
  ambrox: 'أمبروكس',
  ambroxan: 'أمبروكسان',
  'angelica seeds': 'بذور الأنجليكا',
  apple: 'التفاح',
  'apple shisha': 'شيشة التفاح',
  apricot: 'المشمش',
  'aquatic notes': 'نفحات مائية',
  armoise: 'الأرموز',
  aromatic: 'عطري',
  'aromatic notes': 'نفحات عطرية',
  artemisia: 'الشيح',
  'bark saffron': 'قشر الزعفران',
  basil: 'الريحان',
  'bay leaf': 'ورق الغار',
  beeswax: 'شمع العسل',
  benzoin: 'البنزوين',
  bergamot: 'البرغموت',
  berries: 'التوتيات',
  berry: 'التوت',
  birch: 'خشب البتولا',
  'birch flower': 'زهر البتولا',
  'birch wood': 'خشب البتولا',
  biscuit: 'البسكويت',
  'bitter almond': 'اللوز المر',
  'bitter orange': 'البرتقال المر',
  'black cherry': 'الكرز الأسود',
  'black currant': 'الكشمش الأسود',
  'black grape': 'العنب الأسود',
  'black pepper': 'الفلفل الأسود',
  'black raspberry': 'التوت الأسود',
  'black tea': 'الشاي الأسود',
  blackberries: 'العليق',
  blackberry: 'العليق',
  blackcurrant: 'الكشمش الأسود',
  'blood orange': 'البرتقال الدموي',
  'blooming flowers': 'الزهور المتفتحة',
  blossom: 'الأزهار',
  bougainvillea: 'الجهنمية',
  bourbon: 'البوربون',
  'bourbon vanilla': 'فانيليا البوربون',
  'bourbon vetiver': 'نجيل الهند البوربون',
  'brazilian tobacco': 'التبغ البرازيلي',
  'brown sugar': 'السكر البني',
  'bulgarian rose': 'الورد البلغاري',
  butter: 'الزبدة',
  buttercream: 'كريمة الزبدة',
  cacao: 'الكاكاو',
  cade: 'العرعر الأحمر',
  'calabrian bergamot': 'البرغموت الكالابري',
  calone: 'الكالون',
  'candied almond': 'اللوز المسكر',
  'candied fruits': 'الفواكه المسكرة',
  'candied lemon': 'الليمون المسكر',
  candy: 'الحلوى',
  cannabis: 'القنب',
  caramel: 'الكراميل',
  'caramel cream': 'كريمة الكراميل',
  'caramel oud': 'عود الكراميل',
  'caramelized lemon': 'الليمون المكرمل',
  'caramelized sugar': 'السكر المكرمل',
  caraway: 'الكراوية',
  cardamom: 'الهيل',
  cashmeran: 'الكشميران',
  cashmere: 'الكشمير',
  'cashmere musk': 'مسك الكشمير',
  'cashmere wood': 'خشب الكشمير',
  cassis: 'الكاسيس',
  cedar: 'خشب الأرز',
  cedarwood: 'خشب الأرز',
  'celery seed': 'بذور الكرفس',
  'champagne rosé': 'شمبانيا روزيه',
  cherry: 'الكرز',
  'cherry blossom': 'زهر الكرز',
  'cherry jam': 'مربى الكرز',
  chestnut: 'الكستناء',
  'chinese cedarwood': 'خشب الأرز الصيني',
  chocolate: 'الشوكولاتة',
  cinnamon: 'القرفة',
  ciste: 'الشيستوس',
  cistus: 'الشيستوس',
  citron: 'الأترج',
  citrus: 'الحمضيات',
  'citrus notes': 'نفحات حمضية',
  citruses: 'الحمضيات',
  'clary sage': 'مريمية الغابة',
  clove: 'القرنفل',
  cloves: 'القرنفل',
  cocoa: 'الكاكاو',
  coconut: 'جوز الهند',
  'coconut milk': 'حليب جوز الهند',
  'coconut water': 'ماء جوز الهند',
  coffee: 'القهوة',
  'coffee arabica': 'قهوة عربيكا',
  cognac: 'الكونياك',
  cookie: 'الكوكيز',
  'cookie accord': 'تناغم الكوكيز',
  'cookie dough': 'عجينة الكوكيز',
  coriander: 'الكزبرة',
  'cotton accord': 'تناغم القطن',
  'cotton candy': 'غزل البنات',
  'cotton musk': 'مسك القطن',
  coumarin: 'الكومارين',
  cranberry: 'التوت البري الأحمر',
  cream: 'الكريمة',
  'creamy notes': 'نفحات كريمية',
  'crystal moss': 'الطحلب البلوري',
  cumin: 'الكمون',
  cyclamen: 'السيكلامن',
  cypress: 'السرو',
  cypriol: 'السيبريول',
  'damask rose': 'الورد الدمشقي',
  'dark chocolate': 'الشوكولاتة الداكنة',
  'dark spices': 'التوابل الداكنة',
  dates: 'التمر',
  'dates accord': 'تناغم التمر',
  davana: 'الدافانا',
  dewdrop: 'قطرات الندى',
  'dried fruits': 'الفواكه المجففة',
  driftwood: 'الخشب الطافي',
  'dry amber': 'العنبر الجاف',
  'dry birch': 'البتولا الجاف',
  'dry fruits': 'الفواكه المجففة',
  'dry woods': 'الأخشاب الجافة',
  'earthy notes': 'نفحات ترابية',
  'egyptian jasmine': 'الياسمين المصري',
  'egyptian neroli': 'النيرولي المصري',
  elemi: 'الإيليمي',
  eucalyptus: 'الكالبتوس',
  'everlasting flower': 'زهرة الخلود',
  fig: 'التين',
  'fig nectar': 'رحيق التين',
  'fir balsam': 'بلسم التنوب',
  'fir resin': 'راتنج التنوب',
  floral: 'زهري',
  'floral notes': 'نفحات زهرية',
  frangipani: 'الفرانجيباني',
  frankincense: 'اللبان',
  freesia: 'الفريزيا',
  'french clary sage': 'المريمية الفرنسية',
  fresh: 'منعش',
  'fresh floral': 'زهري منعش',
  'fresh florals': 'زهور منعشة',
  'fresh spices': 'توابل منعشة',
  'fresh spicy': 'متبّل منعش',
  'frozen apple': 'التفاح المثلج',
  'frozen rose petals': 'بتلات الورد المثلجة',
  fruits: 'الفواكه',
  fruity: 'فاكهي',
  'fruity accord': 'تناغم فاكهي',
  'fruity accords': 'تناغمات فاكهية',
  'fruity notes': 'نفحات فاكهية',
  galbanum: 'القلبانوم',
  gardenia: 'الغاردينيا',
  'georgian wood': 'الخشب الجورجي',
  georgywood: 'جورجيوود',
  geranium: 'الجيرانيوم',
  ginger: 'الزنجبيل',
  'golden apple': 'التفاح الذهبي',
  'golden marshmallow': 'المارشميلو الذهبي',
  gourmand: 'نفحات شهية',
  grapefruit: 'الجريب فروت',
  'green accords': 'تناغمات خضراء',
  'green apple': 'التفاح الأخضر',
  'green french tobacco': 'التبغ الفرنسي الأخضر',
  'green lemon': 'الليمون الأخضر',
  'green mandarin': 'اليوسفي الأخضر',
  'green notes': 'نفحات خضراء',
  'green pear': 'الكمثرى الخضراء',
  'green tangerine': 'اليوسفي الأخضر',
  'green tea': 'الشاي الأخضر',
  'grey amber': 'العنبر الرمادي',
  'guaiac wood': 'خشب الغاياك',
  guaiacwood: 'خشب الغاياك',
  guava: 'الجوافة',
  'gurjan balsam': 'بلسم الغورجان',
  'gurjum balsam': 'بلسم الغورجان',
  'haiti vetiver': 'نجيل الهند الهايتي',
  'haitian vetiver': 'نجيل الهند الهايتي',
  hazelnut: 'البندق',
  hedione: 'الهيديون',
  heliotrope: 'الهليوتروب',
  herbal: 'الأعشاب',
  honey: 'العسل',
  honeysuckle: 'زهر العسل',
  'ice cream': 'الآيس كريم',
  'iced marine accord': 'تناغم بحري مثلج',
  immortelle: 'الخالدة',
  incense: 'البخور',
  'incense wood': 'خشب البخور',
  'indian jasmine': 'الياسمين الهندي',
  'indian jasmine sambac': 'الياسمين الهندي العربي',
  'indonesian patchouli': 'الباتشولي الإندونيسي',
  iris: 'السوسن',
  'italian bergamot': 'البرغموت الإيطالي',
  'italian lemon': 'الليمون الإيطالي',
  jasmine: 'الياسمين',
  'jasmine sambac': 'الياسمين العربي',
  juniper: 'العرعر',
  'juniper berries': 'حبوب العرعر',
  kumquat: 'الكمكوات',
  labdanum: 'اللابدانوم',
  lavandin: 'اللافاندين',
  lavender: 'اللافندر',
  leather: 'الجلد',
  'leather accord': 'تناغم الجلد',
  lemon: 'الليمون',
  'lemon blossom': 'زهر الليمون',
  'lemon meringue pie': 'فطيرة الليمون والمرينغ',
  'lemon verbena': 'لويزة الليمون',
  lemongrass: 'عشب الليمون',
  licorice: 'عرق السوس',
  lily: 'الزنبق',
  'lily of the valley': 'زنبق الوادي',
  lime: 'الليم',
  limoncello: 'الليمونتشيلو',
  liquor: 'المشروب الكحولي',
  liquorice: 'عرق السوس',
  litchi: 'الليتشي',
  lotus: 'اللوتس',
  luban: 'اللبان',
  lychee: 'الليتشي',
  'madagascar vanilla': 'فانيليا مدغشقر',
  magnolia: 'الماغنوليا',
  mandarin: 'اليوسفي',
  'mandarin orange': 'اليوسفي',
  mango: 'المانجو',
  'maple syrup': 'شراب القيقب',
  'maple wood': 'خشب القيقب',
  marine: 'نفحات بحرية',
  'marine accord': 'تناغم بحري',
  'marine notes': 'نفحات بحرية',
  marshmallow: 'المارشميلو',
  matcha: 'الماتشا',
  mate: 'المتة',
  melon: 'الشمام',
  meringue: 'المرينغ',
  milk: 'الحليب',
  mimosa: 'الميموزا',
  'mineral amber': 'العنبر المعدني',
  'mineral notes': 'نفحات معدنية',
  mint: 'النعناع',
  'mirabelle plum': 'برقوق الميرابيل',
  'moroccan jasmine': 'الياسمين المغربي',
  moss: 'الطحلب',
  muguet: 'زنبق الوادي',
  mugwort: 'درمنة',
  musk: 'المسك',
  myrrh: 'المر',
  nagarmotha: 'الناغارموثا',
  narcissus: 'النرجس',
  'natural oud': 'العود الطبيعي',
  nectarine: 'النكتارين',
  'nepeta notes': 'نفحات النيبيتا',
  neroli: 'النيرولي',
  nutmeg: 'جوزة الطيب',
  nuts: 'المكسرات',
  oak: 'البلوط',
  'oak moss': 'طحلب البلوط',
  oakmoss: 'طحلب البلوط',
  oakwood: 'خشب البلوط',
  olibanum: 'اللبان',
  orange: 'البرتقال',
  'orange blossom': 'زهر البرتقال',
  'orange blossom bud': 'برعم زهر البرتقال',
  'orange dew': 'ندى البرتقال',
  'orange flower': 'زهر البرتقال',
  orchid: 'الأوركيد',
  oriental: 'شرقي',
  'oriental notes': 'نفحات شرقية',
  'oriental spices': 'التوابل الشرقية',
  orris: 'جذور السوسن',
  osmanthus: 'الأوسمانثوس',
  oud: 'العود',
  'oud wood': 'خشب العود',
  ozonic: 'أوزوني',
  'ozonic accord': 'تناغم أوزوني',
  'ozonic florals': 'زهور أوزونية',
  'ozonic notes': 'نفحات أوزونية',
  'palo santo': 'البالو سانتو',
  'panna cotta': 'البانا كوتا',
  'passion fruit': 'فاكهة العاطفة',
  passionflower: 'زهرة العاطفة',
  passionfruit: 'فاكهة العاطفة',
  'pastry cream': 'كريمة المعجنات',
  patchouli: 'الباتشولي',
  'patchouli leaf': 'ورق الباتشولي',
  peach: 'الخوخ',
  'peach blossom': 'زهر الخوخ',
  pear: 'الكمثرى',
  pecan: 'البيكان',
  peony: 'الفاوانيا',
  'peony rose': 'الورد الفاوانيا',
  pepper: 'الفلفل',
  'peru balsam': 'بلسم البيرو',
  petitgrain: 'البيتيغرين',
  pimento: 'الفلفل الحلو',
  pine: 'الصنوبر',
  pineapple: 'الأناناس',
  'pink berries': 'التوت الوردي',
  'pink grapefruit': 'الجريب فروت الوردي',
  'pink pepper': 'الفلفل الوردي',
  'pink peppercorn': 'الفلفل الوردي',
  pistachio: 'الفستق',
  'pistachio cream': 'كريمة الفستق',
  plum: 'البرقوق',
  'plum liquor': 'مشروب البرقوق',
  pomarose: 'البوماروز',
  pomegranate: 'الرمان',
  'pomegranate musk': 'مسك الرمان',
  'powdered sugar': 'سكر البودرة',
  'powdery notes': 'نفحات بودرية',
  praline: 'البرالين',
  'precious woods': 'الأخشاب الثمينة',
  raspberry: 'التوت',
  'red apple': 'التفاح الأحمر',
  'red berries': 'التوتيات الحمراء',
  'red cherry': 'الكرز الأحمر',
  'red cranberry': 'التوت البري الأحمر',
  'red currant': 'الكشمش الأحمر',
  'red fruits': 'الفواكه الحمراء',
  'red rose': 'الورد الأحمر',
  'red thyme': 'الزعتر الأحمر',
  'refreshing spices': 'توابل منعشة',
  resins: 'الراتنجات',
  rhubarb: 'الراوند',
  'roasted tonka': 'التونكا المحمصة',
  'rooibos tea': 'شاي الرويبوس',
  rose: 'الورد',
  'rose milk': 'حليب الورد',
  rosemary: 'إكليل الجبل',
  rum: 'الرم',
  'rum musk': 'مسك الرم',
  'saffiano leather': 'جلد السافيانو',
  saffron: 'الزعفران',
  sage: 'المريمية',
  salt: 'الملح',
  'salted caramel': 'الكراميل المملح',
  'salty notes': 'نفحات مالحة',
  sandalwood: 'خشب الصندل',
  'sea notes': 'نفحات بحرية',
  'sea salt': 'ملح البحر',
  'sichuan pepper': 'فلفل سيتشوان',
  'sicilian lemon': 'الليمون الصقلي',
  smoke: 'الدخان',
  'smoked spices': 'التوابل المدخنة',
  'soft woods': 'الأخشاب الناعمة',
  sorbet: 'السوربيه',
  'spanish cedar': 'الأرز الإسباني',
  'spanish tobacco': 'التبغ الإسباني',
  spice: 'التوابل',
  spices: 'التوابل',
  spicy: 'متبّل',
  'spicy notes': 'نفحات متبّلة',
  strawberry: 'الفراولة',
  'strawberry fizz': 'فوار الفراولة',
  suede: 'الجلد المدبوغ',
  'suede leather': 'الجلد المدبوغ',
  sugar: 'السكر',
  sweet: 'حلو',
  'sweet accord': 'تناغم حلو',
  'sweet almond': 'اللوز الحلو',
  'sweet fruits': 'الفواكه الحلوة',
  'sweet lemon': 'الليمون الحلو',
  'sweet notes': 'نفحات حلوة',
  'sweet orange': 'البرتقال الحلو',
  tangerine: 'اليوسفي',
  tea: 'الشاي',
  'thai basil': 'الريحان التايلاندي',
  thyme: 'الزعتر',
  'timot pepper': 'فلفل التيمور',
  'toasted pistachio': 'الفستق المحمص',
  tobacco: 'التبغ',
  toffee: 'التوفي',
  'tomato leaves': 'أوراق الطماطم',
  tonka: 'التونكا',
  'tonka bean': 'حبوب التونكا',
  'tropical coconut': 'جوز الهند الاستوائي',
  'tropical flowers': 'الزهور الاستوائية',
  'tropical fruits': 'الفواكه الاستوائية',
  'tropical notes': 'نفحات استوائية',
  tuberose: 'التوبروز',
  'turkish damask rose': 'الورد الدمشقي التركي',
  'turkish rose': 'الورد التركي',
  turmeric: 'الكركم',
  'tutti frutti': 'توتي فروتي',
  vanilla: 'الفانيليا',
  'vanilla absolute': 'مطلق الفانيليا',
  'vanilla bean': 'حبوب الفانيليا',
  'vanilla bourbon': 'فانيليا البوربون',
  'vanilla caviar': 'كافيار الفانيليا',
  'vanilla cream': 'كريمة الفانيليا',
  'vanilla syrup': 'شراب الفانيليا',
  'velvet wood': 'الخشب المخملي',
  verbena: 'لويزة',
  vetiver: 'نجيل الهند',
  violet: 'البنفسج',
  'violet leaf': 'ورق البنفسج',
  'violet leaves': 'ورق البنفسج',
  'virginia cedarwood': 'خشب أرز فيرجينيا',
  'warm musk': 'المسك الدافئ',
  'warm woods': 'الأخشاب الدافئة',
  'water lily': 'زنبق الماء',
  watermelon: 'البطيخ الأحمر',
  'whipped cream': 'الكريمة المخفوقة',
  whiskey: 'الويسكي',
  'white amber': 'العنبر الأبيض',
  'white cedarwood': 'خشب الأرز الأبيض',
  'white chocolate': 'الشوكولاتة البيضاء',
  'white floral': 'زهري أبيض',
  'white florals': 'الزهور البيضاء',
  'white flowers': 'الزهور البيضاء',
  'white musk': 'المسك الأبيض',
  'white oud': 'العود الأبيض',
  'white peach': 'الخوخ الأبيض',
  'white pepper': 'الفلفل الأبيض',
  'white rose': 'الورد الأبيض',
  'white tea': 'الشاي الأبيض',
  'white wood': 'الخشب الأبيض',
  'wild berries': 'التوت البري',
  'wild lavender': 'اللافندر البري',
  wine: 'النبيذ',
  wood: 'الخشب',
  woods: 'الأخشاب',
  woody: 'خشبي',
  'woody notes': 'نفحات خشبية',
  'ylang ylang': 'الإيلنغ إيلنغ',
  'ylang-ylang': 'الإيلنغ إيلنغ',
  yuzu: 'اليوزو',
};

/**
 * Scent notes are free text in a product metafield, so a note without a Shopify translation reaches the app in
 * English. Notes are a closed vocabulary, so Arabic readers get them from this glossary; an emoji prefix is kept.
 */
export function localizedNote(note: string, language: string): string {
  const text = note.trim();
  if (language !== 'ar' || !LATIN.test(text)) return note;
  const symbols = LEADING_SYMBOLS.exec(text)?.[0] ?? '';
  const arabic = ARABIC_NOTE_NAMES[text.slice(symbols.length).toLowerCase()];
  return arabic ? `${symbols}${arabic}` : note;
}
